stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
      - src/data/data_collection.py
    outs:
      - data/raw

  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
      - data/raw
      - src/data/data_prep.py
    outs:
      - data/processed

  model_building:
    cmd: python src/models/model_building.py
    deps:
      - data/processed
      - src/models/model_building.py
    outs:
      - models/model.pkl

  model_eval:
    cmd: python src/models/model_eval.py
    deps:
      - models/model.pkl
      - src/models/model_eval.py
    outs:
      - reports/metrics.json